#!/usr/bin/env ansible-playbook
---
- name: "App Deployment: {{ app }}"

  hosts:
    - "vm_tag_{{ app }}"

  become: true
  become_user: root
  tasks:
    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        autoclean: true
      async: 3600
      poll: 5
      when: upgrade_system | default(false) | bool
      tags:
        - system

    - ansible.builtin.import_role:
        name: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
        # main_config_file: ops-agent.config.yml
      tags:
        - google-ops-agent

    - ansible.builtin.import_role:
        name: andreswebs.docker_app
      vars:
        app_name: "{{ app }}"
        app_src: "{{ playbook_dir }}/../../{{ app }}/app/"
        app_dest: "/opt/{{ app }}"

    - name: Check if a reboot is required
      ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify:
        - reboot
      tags:
        - system

  handlers:
    - name: reboot
      ansible.builtin.reboot:
        msg: Maintenance reboot initiated
