#!/usr/bin/env ansible-playbook
---
- name: k3s

  hosts:
    - k3s
    - vm_tag_k3s

  vars:
    kube_config_remote: /etc/rancher/k3s/k3s.yaml
    kube_config_local: /tmp/k3s.yaml

  become: yes
  become_user: root
  tasks:
    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      async: 3600
      poll: 5
      when: upgrade_system | default(false) | bool
      tags:
        - system

    - ansible.builtin.import_role:
        name: k3s

    - name: Check if a reboot is required
      ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify:
        - reboot
      tags:
        - system

  handlers:
    - name: reboot
      ansible.builtin.reboot:
        msg: Maintenance reboot initiated
