---
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    environment:
      - QDRANT_DIR
    ports:
      - 6333:6333
    volumes:
      - "${QDRANT_DIR}/storage:/qdrant/storage:z"
