# https://weaviate.io/developers/weaviate/installation/docker-compose
# https://weaviate.io/developers/weaviate/config-refs/env-vars
# https://github.com/weaviate/weaviate
---
services:
  weaviate:
    image: semitechnologies/weaviate:1.21.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
    restart: always
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true'
      - PERSISTENCE_DATA_PATH='/var/lib/weaviate'
      - DEFAULT_VECTORIZER_MODULE='none'
      - ENABLE_MODULES='text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      - CLUSTER_HOSTNAME=node1
