
---
- name: Install k3s
  ansible.builtin.shell:
    cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ ansible_host }}" sh -s -
    creates: "{{ kube_config_remote }}"
  tags:
    - k3s-install

- name: Fetch kube config
  ansible.builtin.fetch:
    src: "{{ kube_config_remote }}"
    dest: "{{ kube_config_local }}"
    flat: true
  tags:
    - k3s-install
    - k3s-fetch-config

- name: Register k3s host
  ansible.builtin.command:
    cmd: "echo {{ ansible_host }}"
  register: k3s_host
  changed_when: false
  tags:
    - k3s-install
    - k3s-fetch-config

- name: Update local kube config
  ansible.builtin.replace:
    path: "{{ kube_config_local }}"
    after: "server:"
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ k3s_host.stdout }}:6443"
    backup: true
  delegate_to: localhost
  become: no
  tags:
    - k3s-install
    - k3s-fetch-config
