---
name: vaultwarden

# TODO: traefik

networks:
  web:
    name: web

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    networks:
      - web
    environment:
      - WEBSOCKET_ENABLED=true
      - DOMAIN
    volumes:
      - /var/lib/vaultwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.middlewares=redirect-https"
      - "traefik.http.routers.app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.app-secure.entrypoints=web-secure"
      - "traefik.http.routers.app-secure.service=app-secure"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.services.app-secure.loadbalancer.server.port=${APP_PORT}"
