---
name: corteza

networks:
  db:
    name: corteza-db

services:
  db:
    image: postgres:15
    networks: [db]
    restart: always
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "${DB_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    image: cortezaproject/corteza:${VERSION}
    networks: [db]
    restart: always
    depends_on: [db]
    volumes:
      - "${SERVER_DATA_DIR}:/data"
    ports:
      - "${SERVER_PORT}:80"
    environment:
      - DOMAIN
      - VERSION
      - DB_DSN
      - ACTIONLOG_DEBUG
      - LOG_LEVEL
      - LOG_DEBUG
      - AUTH_JWT_SECRET
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
      - SMTP_FROM
