---
name: twentycrm

networks:
  db:
    name: twentycrm-db

services:
  db:
    container_name: twentycrm-db
    image: postgres:${POSTGRES_VERSION:-16.11-alpine}
    restart: always

    environment:
      - PGDATA=${PGDATA:-/var/lib/postgresql/16/docker}
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    volumes:
      - ${POSTGRES_LOCAL_DATA_DIR:-/var/lib/twentycrm/postgresql/data}:${POSTGRES_DATA_DIR:-/var/lib/postgresql/data}

    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -h localhost -d $${POSTGRES_DB}
      timeout: 5s
      interval: 5s
      retries: 10

    networks:
      - db
