---
name: minio

# TODO: traefik

networks:
  web:
    name: minio-web

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    hostname: minio
    command: server --console-address ":${X_MINIO_PORT_CONSOLE}" /data
    networks:
      - web
    # ports:
    #   - "9000:9000"
    #   - "9090:9090"
    volumes:
      - /var/lib/minio:/data
      # - ./data:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SERVER_URL
      - MINIO_UID
      - MINIO_GID
      - MINIO_USERNAME=minio
      - MINIO_GROUPNAME=minio
      - MINIO_VOLUMES=/data
      - X_MINIO_PORT_CONSOLE
      - X_MINIO_PORT_API
    healthcheck:
      test:
        [CMD, curl, -f, "http://localhost:${X_MINIO_POR_API}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
