---
name: minio

## TODO:
# networks:
#   proxy:
#     name: proxy
#     external: true

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    hostname: minio
    command: server --console-address ":${X_MINIO_PORT_CONSOLE}" /data
    ## TODO:
    # networks:
    #   - proxy
    volumes:
      - ${LOCAL_MINIO_DATA_DIR:-/var/lib/minio/data}:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SERVER_URL
      - MINIO_UID
      - MINIO_GID
      - MINIO_USERNAME=minio
      - MINIO_GROUPNAME=minio
      - MINIO_VOLUMES=/data
    healthcheck:
      test:
        [
          CMD,
          curl,
          --fail,
          "http://localhost:${X_MINIO_PORT_API}/minio/health/live",
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    # TODO:
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=proxy
    #   - traefik.http.routers.minio.rule=Host(`${X_MINIO_HOST}`)
    #   - traefik.http.routers.minio.entrypoints=websecure
    #   - traefik.http.routers.minio.service=minio
    #   - traefik.http.routers.minio.tls=true
    #   - traefik.http.routers.minio.tls.certresolver=letsencrypt
    #   - traefik.http.services.minio.loadbalancer.server.port=${APP_PORT}
