---
name: openobserve

networks:
  proxy:
    name: proxy
    external: true

services:
  openobserve:
    container_name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:latest
    user: "2000"
    restart: always
    networks:
      - proxy
    volumes:
      - ${LOCAL_ZO_DATA_DIR:-/var/lib/openobserve/data}:/data
    environment:
      - ZO_ROOT_USER_EMAIL
      - ZO_ROOT_USER_PASSWORD
      - ZO_TELEMETRY
      - ZO_PROMETHEUS_ENABLED
      - ZO_WEB_URL
      - ZO_CLUSTER_COORDINATOR
      - ZO_LOCAL_MODE_STORAGE

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      ## https
      - traefik.http.routers.zo.rule=Host(`${ZO_WEB_URL}`)
      - traefik.http.routers.zo.entrypoints=websecure
      - traefik.http.routers.zo.service=zo
      - traefik.http.routers.zo.tls=true
      - traefik.http.routers.zo.tls.certresolver=letsencrypt
      - traefik.http.services.zo.loadbalancer.server.port=5080
      ## grpc
      - traefik.http.services.zo-grpc.loadbalancer.server.scheme=h2c
      - traefik.http.services.zo-grpc.loadbalancer.server.port=5081
      - traefik.http.routers.zo-grpc.rule=Host(`${ZO_WEB_URL}`)
      - traefik.http.routers.zo-grpc.tls.certresolver=letsencrypt
      - traefik.http.routers.zo-grpc.entrypoints=grpc
      - traefik.http.routers.zo-grpc.service=zo-grpc
