---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vector

resources:
  - ../../base

# https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1951406289
helmCharts:
  - name: vector
    repo: https://helm.vector.dev
    version: 0.33.0
    namespace: vector
    releaseName: vector
    valuesFile: ../../base/vector.helm.values.yaml
    additionalValuesFiles:
      - vector.helm.values.yaml
