---
services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: host
    command: tunnel --no-autoupdate run ${TUNNEL_ID}
    environment:
      - TUNNEL_ID
      - TUNNEL_TOKEN
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
