---
name: jenkins

networks:
  proxy:
    name: proxy
    external: true

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
      - /var/lib/jenkins:/var/jenkins_home
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOST}`)
      - traefik.http.routers.jenkins.entrypoints=websecure
      - traefik.http.routers.jenkins.service=jenkins
      - traefik.http.routers.jenkins.tls=true
      - traefik.http.routers.jenkins.tls.certresolver=letsencrypt
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
