---
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${DATA_DIR}/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - "${PEPPERMINT_UI_PORT}:3000"
      - "${PEPPERMINT_API_PORT}:5003"
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - SECRET
