---
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_DIR
    ports:
      - 11434:11434
    volumes:
      - "${OLLAMA_DIR}:/root/.ollama"
