---
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${DATA_DIR}/data:/var/lib/postgresql/data"
