# https://qryn.metrico.in/#/installation
---
name: qryn

networks:
  web:
    name: web
  db:
    name: db

services:
  qryn:
    container_name: qryn
    image: qxip/qryn:latest
    restart: always
    depends_on:
      - clickhouse-server
    networks:
      - web
      - db
    environment:
      - CLICKHOUSE_SERVER
      - CLICKHOUSE_AUTH
      - CLICKHOUSE_DB

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      ## https
      - "traefik.http.routers.app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.middlewares=redirect-https"
      - "traefik.http.routers.app-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.app-secure.entrypoints=web-secure"
      - "traefik.http.routers.app-secure.service=app-secure"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-secure.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"

  clickhouse-server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server:latest
    restart: always
    networks:
      - db
    environment:
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    healthcheck:
      test: [CMD, wget, --spider, -q, 127.0.0.1:8123/ping]
      interval: 1s
      timeout: 1s
      retries: 30

  traefik:
    container_name: traefik
    image: traefik:v3.1
    restart: always
    networks:
      - web
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/letsencrypt
