---
name: headless-browser

networks:
  headless-browser:
    name: headless-browser

services:
  headless-browser:
    container_name: headless-browser
    image: docker.io/chromedp/headless-shell
    restart: unless-stopped
    ports:
      - 9222:9222
      - 9223:9223
    networks:
      - headless-browser
